#ifndef MAIN_H
#define MAIN_H

#include <Arduino.h>
#include <SPI.h>
#include <SD.h>
#include <string>
#include <sstream>
#include <vector>
#include <Adafruit_GFX.h>
#include <Adafruit_ST7735.h>
#include <RadioLib.h>
#include <TinyGPSPlus.h>
#include <TimeLib.h>
#include <Timezone.h>

#include "gpx.h"

#include "gps_tracker.h"
#include "lora_aprs.h"

// Board definitions
#define REGION_EU868
#define WIRELESS_TRACKER_V2

// Pin definitions
#define PAD_UP_PIN 44
#define PAD_DOWN_PIN 43
#define PAD_LEFT_PIN 45
#define PAD_RIGHT_PIN 46
#define PAD_MIDDLE_PIN 4
#define SD_CS 5
#define SD_MISO 11
#define SD_MOSI 10
#define SD_SCLK 9
#define GPS_ENABLE_PIN 3
#define GPS_RX 33
#define GPS_TX 34
#define BATT_ADC 1 // ADC1_CH0

// Display definitions
#define TFT_LED 21
#define TFT_CS 38
#define TFT_RST 39
#define TFT_DC 40
#define TFT_SCLK 41
#define TFT_MOSI 42

#define DISP_HEIGHT 80
#define DISP_WIDTH 160

// LoRa definitions
#define RADIO_CS_PIN 8
#define RADIO_RST_PIN 12
#define RADIO_DIO1_PIN 14
#define RADIO_BUSY_PIN 13

#define CYCLE_TIME 100 // ms
#define COORD_PRECISION 5 // number of decimal places for coordinates

using namespace std;

enum PadDirection
{
    UP,
    DOWN,
    MIDDLE,
    LEFT,
    RIGHT,
};

enum MenuItems
{
    START_TRACKING,
    SAVE_WAYPOINT,
    SEND_POSITION,
    EXIT,
};

struct BoardConfig // can be overwritten with values from config.txt on SD card
{
    int tracking_interval = 120;     // s
    float tracking_distance = 250.0; // meters
    string track_desc = "Generated by Heltec Tracker V1.1";
    string callsign = "NOCALL";
    string symbol = "[";
    string status = "";
    int position_report_interval = 300; // s
    bool position_reports_enabled = false;
};

// Global objects
TinyGPSPlus gps;
Adafruit_ST7735 disp(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCLK, TFT_RST);
SX1262 radio = new Module(RADIO_CS_PIN, RADIO_DIO1_PIN, RADIO_RST_PIN, RADIO_BUSY_PIN);
LoRaAPRS aprs(&gps, &radio);
GPSTracker tracker(&gps);
BoardConfig boardConfig;
vector<string> menu_items = {
    {"Start Tracking"},
    {"Save Waypoint"},
    {"Send Position"},
    {"Exit"},
};
int int_flag = -1; // flag to indicate which action to take after menu selection

// Timezone settings
TimeChangeRule CEST = {"CEST", Last, Sun, Mar, 2, 120}; // Winter time (UTC + 1)
TimeChangeRule CET = {"CET", Last, Sun, Oct, 3, 60};    // Summer time (UTC + 2)
Timezone timezone_obj(CEST, CET);

// Global variables
bool sd_card_init = false;
volatile int screen_id = 0;
volatile int cursor_pos = 0;
string message_str;
unsigned long prev_millis = 0;
tmElements_t last_gps_time;
string time_str;

// UI methods
void init_display();
void render_screen();
void exit_menu();
void IRAM_ATTR button_handler(int btn_id);
string to_string_rounded(double value, int decimals);
void display_text(int x, int y, const string &text, uint16_t text_color = ST77XX_BLUE, int text_size = 1, uint16_t bg_color = ST77XX_BLACK);
void display_wrapped_text(int x, int y, const string &text, int line_end, uint16_t text_color = ST77XX_BLUE, int text_size = 1, uint16_t bg_color = ST77XX_BLACK);

void run_tasks(uint16_t);
void setup();
void loop();

#endif // MAIN_H