#ifndef MAIN_H
#define MAIN_H

#include <Arduino.h>
#include <SPI.h>
#include <SD.h>
#include <string>
#include <Adafruit_GFX.h>
#include <Adafruit_ST7735.h>
#include <RadioLib.h>
#include <TinyGPSPlus.h>

#include "gpx.h"

#include "gps_tracker.h"
#include "lora_aprs.h"

// Board definitions
#define REGION_EU868
#define WIRELESS_TRACKER_V2

// Pin definitions
#define PAD_UP_PIN 43
#define PAD_DOWN_PIN 44
#define PAD_LEFT_PIN 45
#define PAD_RIGHT_PIN 46
#define PAD_MIDDLE_PIN 4
#define SD_CS 5
#define GPS_ENABLE_PIN 3
#define GPS_RX 33
#define GPS_TX 34
#define BATT_ADC 1 // ADC1_CH0

// Display definitions
#define TFT_LED 21
#define TFT_CS 38
#define TFT_RST 39
#define TFT_DC 40
#define TFT_SCLK 41
#define TFT_MOSI 42

#define DISP_HEIGHT 80
#define DISP_WIDTH 160

// LoRa definitions
#define RADIO_CS_PIN 8
#define RADIO_RST_PIN 12
#define RADIO_DIO1_PIN 14
#define RADIO_BUSY_PIN 13

#define CYCLE_TIME 100 // ms

using namespace std;

enum PadAction
{
    NONE,
    UP,
    DOWN,
    LEFT,
    RIGHT,
    MIDDLE
};

enum MenuItems
{
    START_TRACKING,
    STOP_TRACKING,
    SAVE_WAYPOINT,
    SEND_POSITION,
};

struct BoardConfig // can be overwritten with values from config.txt on SD card
{
    int tracking_interval = 120;     // s
    float tracking_distance = 250.0; // meters
    string track_desc = "Generated by Heltec Tracker V1.1";
    string callsign = "NOCALL";
    string symbol = "[";
    string status = "";
    int position_report_interval = 300; // s
    bool position_reports_enabled = false;
};

// UI methods
void init_display();
void render_screen();
float read_battery_voltage();

// Control methods
PadAction get_action();

void run_tasks(uint16_t);
void setup();
void loop();

#endif // MAIN_H