#include <Arduino.h>
#include "SPI.h"
#include "SD.h"

#include "HT_st7735.h"
#include "HT_TinyGPS++.h"
#include "gpx.h"

#define REGION_EU868
#define WIRELESS_TRACKER_V2

#define PAD_UP 43
#define PAD_DOWN 44
#define PAD_LEFT 45
#define PAD_RIGHT 46
#define PAD_MIDDLE 4
#define SD_CS 5
#define GPS_ENABLE_PIN 3
#define BATT_ADC A0 // ADC1_CH0

TinyGPSPlus GPS;
GPX myGPX;
File GpxFile;
HT_st7735 disp;

bool sd_card_init = false;
int menu_item = 0;

bool begin_tracking()
{
  // set metadata for GPX file
  myGPX.setMetaDesc("FW v0.1");
  myGPX.setName("track-" + (String)GPS.date.year() + (String)GPS.date.month() + (String)GPS.date.day() + "-" + (String)GPS.time.hour() + "_" + (String)GPS.time.minute());
  myGPX.setDesc("Generated by Heltec Tracker V1.1");
  // myGPX.setSrc("GPS Tracker");

  if (sd_card_init)
  {
    // create track file
    GpxFile = SD.open(myGPX.getName() + ".gpx", "w");
    if (GpxFile)
    {
      // write header to the file
      GpxFile.println(myGPX.getOpen());
      GpxFile.println(myGPX.getMetaData());
      GpxFile.println(myGPX.getTrakOpen());
      GpxFile.println(myGPX.getInfo());
      GpxFile.println(myGPX.getTrakSegOpen());
      GpxFile.close();
      return true;
    }
  }

  return false;
}

bool track_point(float lat, float lon, float ele, String time)
{
  if (sd_card_init)
  {
    GpxFile = SD.open(myGPX.getName() + ".gpx", "a");
    if (GpxFile)
    {
      // write a track point to the file
      GpxFile.println(myGPX.getPt(GPX_TRKPT, String(lat), String(lon), String(ele), time));
      GpxFile.close();
      return true;
    }
  }

  return false;
}

bool end_tracking()
{
  if (sd_card_init)
  {
    GpxFile = SD.open(myGPX.getName() + ".gpx", "a");
    if (GpxFile)
    {
      // write footer to the file and close it
      GpxFile.println(myGPX.getTrakSegClose());
      GpxFile.println(myGPX.getTrakClose());
      GpxFile.println(myGPX.getClose());
      GpxFile.close();
      return true;
    }
  }
  return false;
}

void show_menu()
{
  switch (menu_item)
  {
  case 0:
    // draw main screen
    break;

  default:
    break;
  }
}

void setup()
{
  // Setup buttons
  pinMode(PAD_UP, INPUT_PULLUP);
  pinMode(PAD_DOWN, INPUT_PULLUP);
  pinMode(PAD_LEFT, INPUT_PULLUP);
  pinMode(PAD_RIGHT, INPUT_PULLUP);
  pinMode(PAD_MIDDLE, INPUT_PULLUP);

  // Setup ADC for battery monitoring
  pinMode(BATT_ADC, INPUT);

  // Setup GPS
  pinMode(GPS_ENABLE_PIN, OUTPUT);
  digitalWrite(GPS_ENABLE_PIN, HIGH);
  Serial1.begin(115200, SERIAL_8N1, 33, 34);
  Serial.begin(115200);

  // Setup display
  disp.st7735_init();
  disp.st7735_fill_screen(ST7735_BLACK);

  // Setup SD card
  if (!SD.begin(SD_CS))
  {
    disp.st7735_write_str(0, 0, "SD init failed!");
    return;
  }
  Serial.println("SD card success.");
  sd_card_init = true;
}

void loop()
{
  show_menu();

  if (Serial1.available() > 0)
  {
    if (Serial1.peek() != '\n')
    {
      GPS.encode(Serial1.read());
    }
    else
    {
      Serial1.read();

      disp.st7735_fill_screen(ST7735_BLACK);
      disp.st7735_write_str(0, 0, (String) "GPS_test");
      String time_str = (String)GPS.time.hour() + ":" + (String)GPS.time.minute() + ":" + (String)GPS.time.second() + ":" + (String)GPS.time.centisecond();
      disp.st7735_write_str(0, 20, time_str);
      String latitude = "LAT: " + (String)GPS.location.lat();
      disp.st7735_write_str(0, 40, latitude);
      String longitude = "LON: " + (String)GPS.location.lng();
      disp.st7735_write_str(0, 60, longitude);

      Serial.printf("GPS Data: %f %f %f\n", GPS.location.lat(), GPS.location.lng(), GPS.altitude.meters());

      while (Serial1.read() > 0)
        ;
    }
  }
}
