#ifndef MAIN_H
#define MAIN_H

#include <Arduino.h>
#include <SPI.h>
#include <SD.h>

#include "HT_st7735.h"
#include "HT_TinyGPS++.h"
#include "gpx.h"

// Board definitions
#define REGION_EU868
#define WIRELESS_TRACKER_V2

// Pin definitions
#define PAD_UP_PIN 43
#define PAD_DOWN_PIN 44
#define PAD_LEFT_PIN 45
#define PAD_RIGHT_PIN 46
#define PAD_MIDDLE_PIN 4
#define SD_CS 5
#define GPS_ENABLE_PIN 3
#define GPS_RX 33
#define GPS_TX 34
#define BATT_ADC A0 // ADC1_CH0

#define CYCLE_TIME 100 // ms

enum PadAction
{
    NONE,
    UP,
    DOWN,
    LEFT,
    RIGHT,
    MIDDLE
};

struct BoardConfig // can be overwritten with values from config.txt on SD card
{
    int tracking_interval = 60;     // s
    float tracking_distance = 40.0; // meters
    String track_desc = "Generated by Heltec Tracker V1.1";
    String callsign = "NOCALL";
};

struct DateTime
{
    short year;
    int8_t month;
    int8_t day;
    int8_t hour;
    int8_t minute;
    int8_t second;
};

struct RoutePoint
{
    float lat;
    float lon;
    float ele;
    DateTime time;
};

// Tracking methods
bool begin_tracking();
bool track_point(float, float, float);
bool end_tracking();
int time_between(DateTime, DateTime);
DateTime parse_time(String);
String format_time(DateTime);
DateTime get_current_time();

// UI methods
void show_menu();
float read_battery_voltage();

// Control methods
PadAction get_action();

void run_tasks(uint16_t);
void setup();
void loop();

#endif // MAIN_H